// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrientalOasis.DataAccess.Data;

#nullable disable

namespace OrientalOasis.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240612162233_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrientalOasis.Model.Category", b =>
                {
                    b.Property<int>("Cat_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cat_Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Cat_Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Cat_Id = 1,
                            DisplayOrder = 1,
                            Name = "Ceramics"
                        },
                        new
                        {
                            Cat_Id = 2,
                            DisplayOrder = 2,
                            Name = "Paintings"
                        },
                        new
                        {
                            Cat_Id = 3,
                            DisplayOrder = 3,
                            Name = "Sculptures"
                        });
                });

            modelBuilder.Entity("OrientalOasis.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("Cat_Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("Cat_Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Cat_Id = 1,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            ItemName = "Fortune of Time",
                            ItemNumber = "SWD9999001",
                            ListPrice = 99.0,
                            Origin = "Indian",
                            Price = 85.0,
                            Price100 = 50.0,
                            Price50 = 80.0
                        },
                        new
                        {
                            ProductId = 2,
                            Cat_Id = 2,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            ItemName = "Nancy Hoover",
                            ItemNumber = "CAW777777701",
                            ListPrice = 40.0,
                            Origin = "ThaiLand",
                            Price = 25.0,
                            Price100 = 15.0,
                            Price50 = 20.0
                        },
                        new
                        {
                            ProductId = 3,
                            Cat_Id = 3,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            ItemName = "Vanish in the Sunset",
                            ItemNumber = "RITO5555501",
                            ListPrice = 55.0,
                            Origin = "VietName",
                            Price = 50.0,
                            Price100 = 35.0,
                            Price50 = 40.0
                        },
                        new
                        {
                            ProductId = 4,
                            Cat_Id = 1,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            ItemName = "Cotton Candy",
                            ItemNumber = "WS3333333301",
                            ListPrice = 70.0,
                            Origin = "China",
                            Price = 65.0,
                            Price100 = 55.0,
                            Price50 = 60.0
                        },
                        new
                        {
                            ProductId = 5,
                            Cat_Id = 2,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            ItemName = "Rock in the Ocean",
                            ItemNumber = "SOTJ1111111101",
                            ListPrice = 30.0,
                            Origin = "Indonesia",
                            Price = 27.0,
                            Price100 = 20.0,
                            Price50 = 25.0
                        },
                        new
                        {
                            ProductId = 6,
                            Cat_Id = 3,
                            Description = "Praesent vitae sodales libero. Praesent molestie orci augue, vitae euismod velit sollicitudin ac. Praesent vestibulum facilisis nibh ut ultricies.\r\n\r\nNunc malesuada viverra ipsum sit amet tincidunt. ",
                            ItemName = "Leaves and Wonders",
                            ItemNumber = "FOT000000001",
                            ListPrice = 25.0,
                            Origin = "Laura Phantom",
                            Price = 23.0,
                            Price100 = 20.0,
                            Price50 = 22.0
                        });
                });

            modelBuilder.Entity("OrientalOasis.Model.Product", b =>
                {
                    b.HasOne("OrientalOasis.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Cat_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
